baseURL = "https://rodschmidt.com/"
languageCode = "en-us"
title = "Rod Schmidt"
theme = "hyde-hyde"
disqusShortname = "infinitenil"
publishDir = "docs"
canonifyURLs = true
enableRobotsTXT = true

[params]
description = "Thoughts on Software Development"
copyright = "Rod Schmidt"

# Social media links
[params.social]
github = "infinitenil"
twitter = "rodschmidt"
linkedin = "rodschmidt"
stackoverflow = "117435"
gravatar = "rod@infinitenil.com"

[menu]
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"

  [[menu.main]]
    name = "Posts"
    identifier = "posts"
    url = "/posts/"
    #weight = 3
