baseURL = "https://infinitenil.github.io/rodschmidt.com/"
languageCode = "en-us"
title = "Rod Schmidt"
theme = "hyde-hyde"
disqusShortname = "infinitenil"
publishDir = "docs"
canonifyURLs = true

[params]
description = "Thoughts on Software Development"

# Social media links
github = "https://github.com/infinitenil"
twitter = "https://twitter.com/rodschmidt"
linkedin = "https://linkedin.com/in/rodschmidt"
stackoverflow = "http://careers.stackoverflow.com/rodschmidt"

[menu]
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"

  [[menu.main]]
    name = "Archives"
    identifier = "archives"
    url = "/archives/"
    #weight = 3
